--------------------------------------------------------
--  파일이 생성됨 - 금요일-6월-25-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "NOTE"."MEMBER" 
   (	"EMAIL" VARCHAR2(50 BYTE), 
	"PW" VARCHAR2(50 BYTE), 
	"NICKNAME" VARCHAR2(50 BYTE), 
	"ACCOUNTDATE" DATE, 
	"PROFILE" BLOB, 
	"RATING" NUMBER, 
	"WIN" NUMBER, 
	"LOSE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("PROFILE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
REM INSERTING into NOTE.MEMBER
SET DEFINE OFF;
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('1@1.1','1111','1',null,1000,0,0);
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('2@2.2','2222','2',null,1000,0,0);
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('3@3.3','3333','3',null,1000,0,0);
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('4@4.4','4444','4',null,1000,0,0);
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('5@5.5','5555','5',null,1000,0,0);
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('6@6.6','6666','6',null,1000,0,0);
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('7@7.7','7777','7',null,1000,0,0);
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('8@8.8','8888','8',null,1000,0,0);
Insert into NOTE.MEMBER (EMAIL,PW,NICKNAME,ACCOUNTDATE,RATING,WIN,LOSE) values ('9@9.9','9999','9',null,1000,0,0);
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NOTE"."MEMBER_PK" ON "NOTE"."MEMBER" ("EMAIL", "NICKNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "NOTE"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("EMAIL", "NICKNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOTE"."MEMBER" MODIFY ("PW" NOT NULL ENABLE);
  ALTER TABLE "NOTE"."MEMBER" MODIFY ("NICKNAME" NOT NULL ENABLE);
  ALTER TABLE "NOTE"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
